language: node_js
node_js:
  - "0.10"

install:
  - npm install

before_script:
  - npm install -g grunt-cli

script:
  - grunt eslint

branches:
  only:
    - gh-pages
#after_success:
#    - npm run coveralls